# Generated by Django 2.2.12 on 2020-05-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_city',
            field=models.TextField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.TextField(max_length=255, verbose_name='Surname'),
        ),
    ]
