# Generated by Django 2.2.12 on 2020-05-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Point Latitude')),
                ('lon', models.FloatField(verbose_name='Point Longitude')),
                ('is_node', models.BooleanField(default=False, verbose_name='Is Node')),
                ('question', models.TextField(null=True, verbose_name='Question')),
                ('answer', models.TextField(null=True, verbose_name='Answer')),
                ('tip', models.TextField(null=True, verbose_name='Tip')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('points', models.ManyToManyField(to='games.Point')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['-id'],
            },
        ),
    ]
