# Generated by Django 2.2.12 on 2020-05-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('points_lat', models.FloatField(verbose_name='Point Latitude')),
                ('points_lon', models.FloatField(verbose_name='Point Longitude')),
                ('questions', models.TextField(verbose_name='Question')),
                ('answers', models.TextField(verbose_name='Answer')),
                ('tips', models.TextField(verbose_name='Tip')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['-id'],
            },
        ),
    ]
