# Generated by Django 2.2.12 on 2020-06-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentgame',
            name='scores',
            field=models.IntegerField(default=0, verbose_name='Scores'),
        ),
    ]
