# Generated by Django 2.2.12 on 2020-06-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200606_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentgame',
            name='time_completed',
            field=models.DateTimeField(null=True, verbose_name='Time Completed'),
        ),
    ]
