# Generated by Django 2.2.12 on 2020-06-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_currentgame_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='is_help_used',
            field=models.BooleanField(default=False, verbose_name='Is Help Used'),
        ),
        migrations.AddField(
            model_name='result',
            name='is_tip_used',
            field=models.BooleanField(default=False, verbose_name='Is Tip Used'),
        ),
    ]
