# Generated by Django 2.2.12 on 2020-06-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20200607_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultcluster',
            name='time_completed',
            field=models.DateTimeField(null=True, verbose_name='Time Completed'),
        ),
        migrations.AlterField(
            model_name='resultpoint',
            name='time_completed',
            field=models.DateTimeField(null=True, verbose_name='Time Completed'),
        ),
    ]
