# Generated by Django 2.2.12 on 2020-06-12 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20200608_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultpoint',
            name='is_checked_correctly',
        ),
    ]
