# Generated by Django 2.2.12 on 2020-06-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_resultpoint_is_checked_correctly'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultpoint',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Is Checked'),
        ),
    ]
